# Generated by Django 5.2.6 on 2025-09-30 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie (max 100 caractères)', max_length=100)),
                ('user', models.ForeignKey(help_text='Utilisateur créateur de la catégorie', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre de la tâche (max 200 caractères)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée (optionnel)')),
                ('due_date', models.DateTimeField(blank=True, help_text="Date d'échéance de la tâche (optionnel)", null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Indique si la tâche est terminée')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priorité de la tâche (faible, moyenne, haute)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la tâche')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour')),
                ('category', models.ForeignKey(blank=True, help_text='Catégorie de la tâche (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.category')),
                ('user', models.ForeignKey(help_text='Utilisateur assigné à la tâche', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-created_at'],
            },
        ),
    ]
