# Generated by Django 5.2.6 on 2025-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Date de création de la catégorie', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la catégorie (optionnel)'),
        ),
    ]
