# Generated by Django 5.2.6 on 2025-09-30 18:56

from django.db import migrations, models
from django.utils import timezone


def populate_created_at(apps, schema_editor):
    """Remplit les valeurs NULL de created_at avec la date actuelle"""
    Category = apps.get_model('tasks', 'Category')
    Category.objects.filter(created_at__isnull=True).update(created_at=timezone.now())


def reverse_populate_created_at(apps, schema_editor):
    """Opération inverse - remet les valeurs à NULL"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_created_at_category_description'),
    ]

    operations = [
        migrations.RunPython(populate_created_at, reverse_populate_created_at),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date de création de la catégorie'),
        ),
    ]
