# Generated by Django 5.2.6 on 2025-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_reminded',
            field=models.BooleanField(default=False, help_text='Indique si un rappel email a été envoyé'),
        ),
    ]
